services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kexibq528123
      - MYSQL_DATABASE=spring_boot_mysql
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./docker/volume_mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"